name: Check
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.12.0"
          cache: yarn
      - uses: foundry-rs/foundry-toolchain@v1
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn check
      - run: yarn build
